spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/default
    username: postgres
    password: postgres
  application:
    name: StudentManager
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
  port: 9090